# Variables that need to be setup manually
redmine_db_postgres: "{{ vault_pg_host }}"

# Variables from "all" group
redmine_db_database: "{{ pg_database }}"
redmine_db_username: "{{ pg_user }}"
redmine_db_password: "{{ pg_password }}"
redmine_db_port: "{{ pg_port }}"

# Default variables

redmine_env_file_path: "/tmp/redmine.env"

pip_install_packages:
  - name: docker
    state: latest