pip_install_packages:
  - name: docker
    state: latest

redmine:
  env_file_path: "/tmp/redmine.env"

  database:
    host: "{{ vault.redmine.database.host }}" # Set manually

    # These variables are set by the group "all"
    name: "{{ postgres_database }}"
    username: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    port: "{{ postgres_port }}"
